name: wine-quality-prediction
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          echo "does gpu exist" > report.md
          cat metrics.txt >> report.md
          cml publish plot.png --md >> report.md
          cml send-comment report.md
