name: wine-quality-prediction
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt install -y nodejs npm libcairo2-dev libfontconfig-dev   libgif-dev libjpeg-dev libpango1.0-dev librsvg2-dev
          npm i -g @dvcorg/cml
          
          pip3 install -r requirements.txt
          python3 train.py
          cat metrics.txt >> report.md
          cml publish plot.png --md >> report.md
          cml send-comment report.md
