name: wine-quality-prediction
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nvidia-smi >> report.md
          cml send-comment report.md
